# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc812fce0489dbc051b832e4ac840e083440c7769e3f1835926784fb84e41c534ea7c84ff9a3c5d98d691810e0ca49a0c497f9459f5db896df737cb1ffb42b30

test:
  secret_key_base: bee7adf8ac52609fd866495224440c88557695d018fab3d4b6e6f57e7584bc0fbd4eea75b9cff4bdab9489b521ea417b95674f733fba0992e5691f6bfe91fd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
